### ISSUE TITLE
`asymmetric` for type discriminators; enumerations

### ISSUE THREAD

**Issue by clord** [stepchowfun/typical#498]
**Description**

in the following example:

```
function area(shape: Types.ShapeIn): number {
  switch (shape.$field) {
    case 'square':
      return shape.square.sideLength * shape.square.sideLength;
    case 'rectangle':
      return shape.rectangle.width * shape.rectangle.height;
    case 'circle':
      return Math.PI * shape.circle.radius * shape.circle.radius;
    default:
      return unreachable(shape);
  }
}
```

note the unreachable case will be hit if a new field is added; whereas, we want to be able to add new types without hitting exceptions. In such a situation, we'd need a 'default' type that consumers already implement and fall back to if the incoming type is not supported — if we mark the discriminator somehow with 'asymmetric'

**Alternatives considered**

- No change; accepting the runtime error when new enums and types are added. That is to say, use `default` as the missing branch.

**Additional context**

I think this is a special case of the problem of enumerations. They also need something like the above proposal if we want to be tolerant of new values without causing failure, if the project wants to have the notion of 'fallback default types and enums.'

**Comment by clord** [comment]
To be clear, I want this for documentation more than anything, which types are expected to grow (and hence we need to not throw), and which are meant to be total (and so we can assert on them when they hit an unexpected case)

so maybe the 'ask' is to be able to nominate one of the options to be the 'default' case for unknown runtime-supplied options, or to nominate certain options get mapped to that default, but are not available to create (for the remove case).

**Comment by stepchowfun** [comment]
Hello, thank you for starting this discussion!

> note the unreachable case will be hit if a new field is added

Apologies if you already know this, but I want to clarify one thing: the unreachable case will be hit if a new `required` field is added. So you are supposed to first add the field as `asymmetric`, then only promote it to required after the `switch` statement has been updated to handle the new case (and the updated code is "active", e.g., deployed to production).

> To be clear, I want this for documentation more than anything, which types are expected to grow (and hence we need to not throw), and which are meant to be total (and so we can assert on them when they hit an unexpected case)

Typical's design generally assumes that any type might grow in the future, but only in a safe way: new fields are `asymmetric` before they are `required`.

> so maybe the 'ask' is to be able to nominate one of the options to be the 'default' case for unknown runtime-supplied options, or to nominate certain options get mapped to that default, but are not available to create (for the remove case).

There is already something like this, but it works a bit differently than the traditional idea of having a default case in the `switch` statement: with `asymmetric` (and `optional`) fields in `choice`s, the writer (rather than the reader in its `switch` statement) has to specify the fallback. In case you haven't seen it (it might be easy to miss), [here](https://github.com/stepchowfun/typical?tab=readme-ov-file#choices-can-have-optional-and-asymmetric-fields-too) is the relevant documentation on how `asymmetric` works in `choice`s.

So I think I'm a bit confused by the question—I think what you're asking for already exists. In the schema file you can declare the cases (called "fields" in the documentation) as `asymmetric`, and doing so has the effect of giving you a safe path to introducing new cases in the future without breaking anything.

**Comment by clord** [comment]
ok, I think i just missed this:

```rust
    # To be promoted to required in the future
    asymmetric please_try_again = 3
```

**Comment by clord** [comment]
What I wanted to model from an existing system is to control how options degrade. e.g., `please_try_again` should decay to `error` and not to an `unreachable` assertion in typescript. 

it sounds like it's on the caller to provide the fallback if it's `asymmetric`, which works for me.
